### ISSUE TITLE
vietnamese is not correctly transformed to IPA

### ISSUE THREAD

**Issue by LinguList** [lexibank/duonglachi#2]
I just checked with a description of the [alphabet](https://en.wikipedia.org/wiki/Vietnamese_alphabet). It may be possible to make a raw conversion to IPA based on this information. Otherwise, it may be added in the notes, or one can discard vietnamese and add it to the concepticon.

**Comment by LinguList** [comment]
In addition, one should check with the profile that was written for [wold](https://github.com/lexibank/wold).

**Comment by LinguList** [comment]
Even easier may be to give [Kirby's vphon](https://github.com/kirbyj/vPhon) a try.

**Comment by CMUgarte** [comment]
I believe this issue is done. If you agree, we can close this issue, @LinguList.

**Comment by LinguList** [comment]
Thanks!
